### ISSUE TITLE
Build the APIHandler class, for providing direct access to the Luno platform

### ISSUE THREAD

**Issue by lorenzorota** [aberdeen-jacobs/luno-trading-bot#6]
Should provide a variety of methods for fetching data from and pushing data to the Luno platform.
Create methods for the most useful API calls such that any communication to and from the platform can be achieved solely through the APIHandler.

The APIHandler will handle any data of the `dict` type, and will be used as a middle-man for creating useful data for the plugins in a dedicated class, for example in the DataParser class, as suggested in the architecture design (just an idea)

**Important**:
* Very important to load the API key and secret from a file and not hardcoded into the code (perhaps you could make a start to the config file from which important settings and credentials will be read and stored, in whatever useful format you prefer e.g. yaml, ini, json)

**Comment by ikabadzhov** [comment]
we can still use the API :) I am busy these days to explore it more
